### ISSUE TITLE
Current status of qcrms

### ISSUE THREAD

**Issue by hh1985** [computational-metabolomics/qcrms#7]
Hi,

What's the current status of the R package?  I'm looking for a wrapped solution to process LC-MS data and want to know if I can use the package to generate QC report.

Thanks,

hanh1985

**Comment by andzajan** [comment]
Hi @hh1985, thenk you for your interest. Version currently on `master` is working with pmp release [0.2.5](https://github.com/computational-metabolomics/pmp/releases/tag/v0.2.5).

Tools is designed to provide QC assesment on XCMS outputs, it doesn't do any LC-MS processing itself. 

We are currently in process of some improvements to the code base and writing up a documentation.
